name: CytrilClan
version: 1.0.0
main: com.cytril.cytrilclan.CytrilClan
api-version: '1.21'
depend: [LuckPerms]
softdepend: [PlaceholderAPI]
commands:
  clan:
    description: Perintah utama CytrilClan
    aliases: [c, clans]
permissions:
  cytrilclan.create:
    description: Izin membuat clan baru
    default: op
  cytrilclan.admin:
    description: Access admin clan commands
    default: op
